################################################################################
# Copyright (c) 2013-2015 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
################################################################################
#
# Objective:
#    Demonstrate constructing the heat resource OS::Heat::Stack
#    This resource allows inlining a HEAT template
#
# Pre-Reqs:
#    None
#
# Mandatory Template Parameters:
#    None
#
# Tenant Considerations:
#    None
#
# Sample CLI syntax:
#    heat stack-create -f OS_Heat_Stack.yaml   STAK
#
# Expected Outcome:
#    2 HEAT stacks (one stack owns the second stack)
#        heat stack-list
#
#    A new keypair called InlineKP (created by the second stack).
#        nova keypair-list
#
################################################################################

heat_template_version: 2015-04-30

description: >
   Demonstrate the OS::Heat::Stack heat resource

resources:
    KeyPair_Stack:
        type: OS::Heat::Stack
        properties:

            template: |
                heat_template_version: 2015-04-30
                parameters:
                    NEW_KEY_NAME:
                        description: Name for the new keypair
                        type: string
                resources:
                    OS_Nova_KeyPair:
                        type: OS::Nova::KeyPair
                        properties:
                            name: { get_param: NEW_KEY_NAME }


            parameters: { NEW_KEY_NAME: InlineKP }
            # context:
            #     - region:
            timeout: 1
